/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123625-gfd9f1e9c52-20260326"
#endif /* AVUTIL_FFVERSION_H */
